language: go
go:
- 1.12.x
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
script:
  - golangci-lint run --disable-all --enable=vet --enable=ineffassign --enable=goconst --tests ./...
  - go test -v -race ./...
